### ISSUE TITLE
Optimizing gallery mode

### ISSUE THREAD

**Issue by Xrey274** [LotuxPunk/Nicephore#16] opened 2021-11-14 17:54 UTC
It's a nice feature, however i can feel slight latency as I scroll though pages. It's not like I have slow pc.

**Comment by LotuxPunk** [comment] 2021-11-14 19:25
Hello !

Indeed, I get what you mean. The problem is, I don't know how to improve that thing, otherwise it'd already implemented.

The latency can come from the loading from an hard drive, the way that I'm displaying the picture as a resource in Minecraft or even from Minecraft itself that isn't really made by design for this kind of feature.

I keep this open for the moment and will try to ask some forge guys how I can do this better, but I'm not sure I can improve it more than it is right now.

**Comment by Xrey274** [comment] 2021-11-18 13:04
Any progress on this?

**Comment by LotuxPunk** [comment] 2021-11-18 13:05
There's some plan to improve the loading, I will communicate on this as soon tests are made.

**Comment by Xrey274** [comment] 2021-11-18 13:07
Sure, thanks. Also btw is ModMenu integration planned in the near future? It shouldn't be too hard and it would a lot more convenient to change the config options.

**Comment by LotuxPunk** [comment] 2021-11-18 13:09
There's no plan actually, but I'm open to the idea as long it's optional.

If you really want that kind of stuff I'd recommend to create a separate issue to keep this one focus on the gallery optimization. 😅

**Comment by LotuxPunk** [comment] 2021-11-18 13:12
Indeed, my bad.

Will have a look at it once the current version is stable. 👍

**Comment by LotuxPunk** [comment] 2021-12-15 08:40
Hey !

Tiny retrospective on that :
A lot of memory leaks and performances issues have been fixed and can be found here : https://github.com/LotuxPunk/Nicephore/commit/2e61600aeb4450d3394d84fe30697bda832a2814

To test this fixes, I only opened the F3 debug and opened GUI on top of it and looked at FPS, it was decreasing at the time because of these issues.

The small latency on page switching isn't really solved yet, but it's way better now that the memory leaks are solved. I will close this for now, but be sure that if I can optimise the mod further, will do !

Thanks again for your feedback

**Closed as completed by LotuxPunk** 2021-12-15 08:40 UTC
Labels: enhancement
